version: '3.9'


volumes:
    gradana_data: {}

services:
    influxdb:
      image: tutum/influxdb:0.9
      restart: always
      environment:
          - PRE_CREATE_DB=cadvisor
      ports:
          - 8083:8083
          - 8086:8086
      volumes:
          - ./data/influxdb:/data    

    cadvisor:
      image: google/cadvisor
      links:
        - influxdb:influxsrv
      command: -storage_driver=influxdb   -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
      restart: always
      ports:
        - "8888:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock:rw
        - /var/lib/docker:/var/lib/docker:ro

    grafana:
      image: grafana/grafana
      user: "104"
      restart: always
      links:
        - influxdb:influxsrv
      ports:
        - "3333:3000"
      volumes:
        - ./grafana_data:/var/lib/grafana
      environment:
        - HTTP_USER=admin
        - HTTP_PASS=admin
        - INFLUXDB_HOST=influxsrv
        - INFLUXDB_PORT=8086'

    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/data:/prometheus
        - ./prometheus/machine-id:/etc/machine-id:ro
      ports:
        - 9090:9090